# C:\app\streamlit_financial_dashboard\.streamlit\secrets.toml

NEO4J_URI = "neo4j+s://f9f444b7.databases.neo4j.io"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "BhpVJhR0i8NxbDPU29OtvveNE8Wx3X2axPI7mS7zXW0"